### ISSUE TITLE
Specify bin location

### ISSUE THREAD

**Issue by xtfer** [platformsh/platformsh-example-drupal8#33]
I've seen a few issues where people have the wrong bin location for Composer, usually in their .environment file. 

Is it worth explicitly setting this using [bin-dir](https://getcomposer.org/doc/articles/vendor-binaries.md#can-vendor-binaries-be-installed-somewhere-other-than-vendor-bin-), and noting that in the .environment file as well?

**Comment by Crell** [comment]
Handled via #45 Thanks.
