### ISSUE TITLE
Drush ~9.0.0 not working within Platform.sh

### ISSUE THREAD

**Issue by idiazroncero** [platformsh/platformsh-example-drupal8#47]
Hello there;

I just wanted to point to an issue with Drush versions. 

I started a Drupal project on Platform.sh using a copy of .platform.app.yaml prior to the following commit (https://github.com/platformsh/platformsh-example-drupal8/commit/654407e1f4583860d9ccafda9149fed6da55fd9d), so my local and Platform versions of drush were 8.x at the moment.

Then, a few days ago, a composer.json update (composer update) automatically upgraded Drush to the ~9.0 version and instantly the deploy process (drush cr, drush updb, etc...) started to fail with a permissions issue:

`Directory /app exists but is not writable. Check directory permissions`

No changes were made to mounts, config files, etc...

Manually reverting drush to 8.x version on Composer.json solved the issue.

I don't know if this issue will affect everybody else, but it seems likely.

**Comment by pjcdawkins** [comment]
I guess the example needs to add a mount for `.drush` (`/app/.drush`), because Drush 9 really wants to write files there.

**Comment by pjcdawkins** [comment]
Without that mount, try Drush `9.0.0-rc1` (instead of earlier versions of 9)

Because I think this was fixed in https://github.com/drush-ops/drush/pull/3160. It looks like Drush 9.0.0-rc1 will now try to create a cache directory in `$HOME/.drush/cache` (`/app/.drush/cache`), and if that fails, it will fall back to `/tmp/drush-$USER/cache` (`/tmp/drush-web/cache`).

**Comment by pjcdawkins** [comment]
... actually I've tried it, it still doesn't work. The mount for /app/.drush is required.

**Comment by idiazroncero** [comment]
Ok, many thanks! The fix is easy enough, so i will try adding that mount.

Thanks for your amazingly swift response!
