### ISSUE TITLE
What to look out for if a project is using `hussainweb/drupal-composer-init` instead of `drupal-composer/drupal-project`

### ISSUE THREAD

**Issue by marcusx** [platformsh/platformsh-example-drupal8#62]
If a project was built with: 

https://www.drupal.org/docs/develop/using-composer/using-composer-to-manage-drupal-site-dependencies#download-core-option-b

And ist using https://github.com/hussainweb/drupal-composer-init 
instead of https://github.com/drupal-composer/drupal-project as a blueprint.

What are the changes in the platform.sh setup I need to take into account? e.g. `drush` is not living in its own top-level directory. What changes need to be done for the setup scripts?

**Comment by Crell** [comment]
Huh.  I only just saw that version for the first time.  It's unfortunate that Drupal has multiple Composer mechanisms.  That only makes life harder for everyone. :frowning: 

From a quick glance I don't see much that's different, assuming the default settings.  The docroot is still `web`.  Drush and Console are both installed via Composer, as they should be.  You'll need the `.environment` file from this repo, and the Platform config files of course, but the biggies appear to be the same.  

So yeah, if you have to work from that base just steal the appropriate files from this repo and you should be pretty close.  (.environment, Psh config, settings.php, settings.platformsh.php).
